class RajeshHimaGF
{
    public static void main(String[]args)
    {
	byte rGF=5;
	short hGF=1;
	int tot=rGF+hGF;
	System.out.println(tot);//6
	System.out.println();
	System.out.println("Rajesh has"+rGF+  "girlfriends");//Rajesh has 5 girlfriends
	System.out.println();
	System.out.println("Hima has"+hGF+"girlfriend");//Hima has 1 girlfriend
	System.out.println();
	System.out.println("Totally"+tot+"girls");//Totally 6 girls
	System.out.println();
	System.out.println();
	System.out.println();
	System.out.println();
    }
}